const missionConfig = {
  themeTitle: "🚀 Mission: Interstellar Rocket Launch",
  questions: [
    { type: "text", question: "1. Rocket Alpha needs 45 fuel units. It currently has 28. How many more does it need?", answer: "17" },
    { type: "text", question: "2. 36 oxygen tanks loaded in sector A + 29 in sector B = _____ total tanks", answer: "65" },
    { type: "text", question: "3. 84 heat shields minus 37 damaged shields leaves _____ functional shields", answer: "47" },
    { type: "text", question: "4. Double 18 battery power cells = _____ total energy capacity", answer: "36" },
    { type: "text", question: "5. Half of a 52-unit liquid hydrogen reserve = _____ units", answer: "26" },
    { type: "text", question: "6. 7 thruster rows × 4 nozzles each = _____ total nozzles", answer: "28" },
    { type: "text", question: "7. 6 stages × 5 guidance microchips = _____ total chips", answer: "30" },
    { type: "text", question: "8. 9 sensor beams × 3 telemetry links = _____ total links", answer: "27" },
    { type: "text", question: "9. 63 countdown seconds - 19 emergency holds = _____", answer: "44" },
    { type: "text", question: "10. 58 structural panels + 26 titanium bolts = _____", answer: "84" },
    { type: "text", question: "11. Complete the launch frequency pattern: 4, 9, 14, 19, _____, 29", answer: "24" },
    { type: "text", question: "12. Complete the thruster pulse sequence: 3, 6, 12, 24, _____", answer: "48" },
    { type: "mcq", question: "13. Gyroscope spin cycle: [CW, CW, CCW, CW, CW, CCW...]. What is the 14th rotation vector?", options: ["CW", "CCW"], answer: "CW" },
    { type: "mcq", question: "14. Which payload serial number does NOT belong in the sequence? [14, 21, 28, 35, 40, 49]", options: ["28", "35", "40", "49"], answer: "40" },
    { type: "text", question: "15. Thruster Valve A pulses every 2 sec, Valve B every 3 sec. Next sync pulse at: _____ sec", answer: "6" },
    { type: "text", question: "16. Communications code sequence: A ➔ D ➔ G ➔ J ➔ _____ (Type the next letter)", answer: "M" },
    { type: "text", question: "17. Altitude voltage step-down sequence: 100, 91, 82, 73, _____", answer: "64" },
    { type: "text", question: "18. Quantum memory block storage capacity: 1, 4, 9, 16, 25, _____", answer: "36" },
    { type: "text", question: "19. A laser tracking beam hits a mirror at 30°. It reflects at 30°. If the mirror turns 15° more, the new angle of reflection is _____°", answer: "45" },
    { type: "text", question: "20. A control lever applies 10 lbs of force on a 4-foot steering arm. Total torque = _____ ft-lbs", answer: "40" },
    { type: "text", question: "21. Engine coolant is at 38°C and vaporizes at 100°C. Degrees remaining until vaporization: _____°C", answer: "62" },
    { type: "text", question: "22. Three 6-Volt rocket telemetry batteries connected in series (+ to -) produce _____ Volts total", answer: "18" },
    { type: "text", question: "23. Gravity on Planet X is half of Earth's. Cargo module is 84 kg on Earth. On Planet X it weighs _____ kg", answer: "42" },
    { type: "text", question: "24. Solar array wings convert 20% of sunlight into power. 500 Watts of sunlight yields _____ Watts", answer: "100" },
    { type: "text", question: "25. Primary Gear A (10 teeth) turns 6 full times, driving Secondary Gear B (30 teeth). Gear B turns _____ times", answer: "2" },
    { type: "mcq", question: "26. CLUES: Four Astronauts (Astra, Buzz, Cosmos, Delta) have four roles: Pilot, Engineer, Commander, Navigator.\n• Astra is NOT the Engineer and NOT the Navigator.\n• Buzz is the Commander.\n• Cosmos suffers from space sickness near engines.\n• Delta's role starts with the letter 'P'.\n\nWhich astronaut is the Commander?", options: ["Astra", "Buzz", "Cosmos", "Delta"], answer: "Buzz" },
    { type: "mcq", question: "27. Based on the clues in the previous question, which astronaut is the Pilot?", options: ["Astra", "Buzz", "Cosmos", "Delta"], answer: "Delta" },
    { type: "mcq", question: "28. Based on the same clues, which astronaut is the Navigator?", options: ["Astra", "Buzz", "Cosmos", "Delta"], answer: "Cosmos" },
    { type: "mcq", question: "29. Based on the same clues, which astronaut is the Engineer?", options: ["Astra", "Buzz", "Cosmos", "Delta"], answer: "Astra" },
    { type: "text", question: "30. If the Engineer works 4 hrs/day on life support and the Pilot works 6 hrs/day on flight paths, how many total hours do both work combined in 5 days?", answer: "50" },
    { type: "text", question: "31. Rocket Computer Function: [Input RPM] ➔ [× 4] ➔ [- 7] ➔ [Output Thrust]. Input = 8, Output = _____", answer: "25" },
    { type: "text", question: "32. Reverse Guidance Matrix: [Input] ➔ [× 3] ➔ [+ 5] ➔ Output: 26. Input = _____", answer: "7" },
    { type: "text", question: "33. Booster Alpha charges at 15%/hr. Booster Beta charges at 25%/hr. After 3 hours, Beta is _____% ahead of Alpha.", answer: "30" },
    { type: "mcq", question: "34. An escape pod holds up to 200 kg. Can it hold 3 astronauts (45 kg each) + a 55 kg emergency survival kit?", options: ["YES", "NO"], answer: "YES" },
    { type: "text", question: "35. If a rocket travels 360 miles in 6 hours at a steady pace, how many miles does it travel in 1 hour?", answer: "60" },
    { type: "text", question: "36. A docking tunnel requires 12 sections. Each section takes 4 minutes to lock. Total lock time = _____ minutes", answer: "48" },
    { type: "text", question: "37. Radiation shielding blocks 85% of cosmic rays. What percentage gets through?", answer: "15" },
    { type: "text", question: "38. A satellite orbits Earth once every 90 minutes. How many full orbits does it complete in 450 minutes?", answer: "5" },
    { type: "text", question: "39. If 3 countdown computers process 45 errors per minute combined, how many errors does 1 computer process per minute?", answer: "15" },
    { type: "text", question: "40. BOSS BATTLE: Find the 4-Digit Launch Master Code [W, X, Y, Z]:\n• Clue 1: All digits are distinct single digits (1-9).\n• Clue 2: W + X + Y + Z = 20.\n• Clue 3: W is the smallest prime number.\n• Clue 4: X is 3 times W.\n• Clue 5: Y is an odd square number.\n\nType the final 4-digit code:", answer: "2693" }
  ]
};
