// Marty Grade 2 Enrichment v1
// Backward-compatible with the existing worksheet app.
// New metadata fields are intentionally ignored by the current UI,
// but can support future filtering/adaptive practice.
//
// Parent workflow:
// 1. Marty solves independently.
// 2. Marty may use the hint if needed.
// 3. Review missed/interesting questions together.
// 4. Use thinkingPrompt during review rather than grading the explanation.
//
// Difficulty:
// 1 = fluency, 2 = strategy/reasoning, 3 = multi-step, 4 = challenge.
// challenge=true marks deliberately harder "Boss" style questions.
const missionConfig = {
    themeTitle: "🧠 Marty's Learning Lab: Grade 2 Missions",
    themeColor: "linear-gradient(135deg, #0284c7 0%, #4f46e5 50%, #9333ea 100%)",
    themeIcon: "🤖",
    showStreakCounter: true,
    streakCounter: true,
    enableStreakBonus: true,
    streakThreshold: 3,
    questions: [
        {
            id: "math-001",
            type: "text",
            category: "math",
            skill: "mental_addition",
            difficulty: 2,
            challenge: false,
            question: "Marty is loading power cells. Cell A has <b>96</b> energy units and Cell B has <b>38</b>. How many energy units does he have altogether?",
            answer: "134",
            hint: "Can you make 96 into a friendly number such as 100?",
            explanation: "One efficient strategy is 96 + 4 = 100, then 34 more makes 134.",
            thinkingPrompt: "Can you solve it another way?"
        },
        {
            id: "math-002",
            type: "text",
            category: "math",
            skill: "mental_subtraction",
            difficulty: 2,
            challenge: false,
            question: "A robot needs <b>324</b> power points to activate. It has <b>286</b>. How many more points does it need?",
            answer: "38",
            hint: "Think of the distance from 286 to 324. You could jump to 300 first.",
            explanation: "286 to 300 is 14, and 300 to 324 is 24. 14 + 24 = 38.",
            thinkingPrompt: "Why can counting up sometimes be easier than subtracting?"
        },
        {
            id: "math-003",
            type: "text",
            category: "math",
            skill: "perimeter",
            difficulty: 2,
            challenge: false,
            question: "A robot testing zone has six outer sides measuring <b>15 ft, 10 ft, 8 ft, 7 ft, 5 ft, and 15 ft</b>. What is the total perimeter?",
            answer: "60",
            hint: "Perimeter means the distance all the way around. Add every outside side.",
            explanation: "15 + 10 + 8 + 7 + 5 + 15 = 60 feet.",
            thinkingPrompt: "What would happen to the perimeter if every side became twice as long?"
        },
        {
            id: "math-004",
            type: "text",
            category: "math",
            skill: "near_doubles",
            difficulty: 1,
            challenge: false,
            question: "Marty collects <b>48</b> crystals on one floor and <b>49</b> on another. How many crystals does he have?",
            answer: "97",
            hint: "48 and 49 are almost doubles. Double 48 first.",
            explanation: "48 + 49 = 48 + 48 + 1 = 97.",
            thinkingPrompt: "Could you use 50 to make this even easier?"
        },
        {
            id: "math-005",
            type: "mcq",
            category: "math",
            skill: "rounding",
            difficulty: 1,
            challenge: false,
            question: "A scanner reads <b>762</b> units. What is 762 rounded to the nearest hundred?",
            options: ["700", "750", "800", "900"],
            answer: "800",
            hint: "Look at the tens digit. Is 762 closer to 700 or 800?",
            explanation: "762 is 38 away from 800 and 62 away from 700, so it rounds to 800.",
            thinkingPrompt: "What is the smallest number that would round to 800?"
        },
        {
            id: "math-006",
            type: "text",
            category: "math",
            skill: "distributive_multiplication",
            difficulty: 2,
            challenge: false,
            question: "A robot uses <b>7</b> energy cells on each of <b>14</b> missions. How many cells does it use altogether?",
            answer: "98",
            hint: "Break 14 into friendly parts such as 10 and 4.",
            explanation: "7 × 14 = 7 × 10 + 7 × 4 = 70 + 28 = 98.",
            thinkingPrompt: "What other way could you calculate 7 × 14?"
        },
        {
            id: "math-007",
            type: "mcq",
            category: "math",
            skill: "factors",
            difficulty: 2,
            challenge: false,
            question: "Which number is <b>composite</b>: 17, 23, 27, or 31?",
            options: ["17", "23", "27", "31"],
            answer: "27",
            hint: "A composite number can be made by multiplying two whole numbers greater than 1.",
            explanation: "27 = 3 × 9, so it has factors besides 1 and itself.",
            thinkingPrompt: "How could you quickly test whether a number is composite?"
        },
        {
            id: "math-008",
            type: "text",
            category: "math",
            skill: "division",
            difficulty: 2,
            challenge: false,
            question: "There are <b>96</b> robot keys shared equally among <b>6</b> doors. How many keys go to each door?",
            answer: "16",
            hint: "You can split 96 into 60 and 36, both easy to divide by 6.",
            explanation: "60 ÷ 6 = 10 and 36 ÷ 6 = 6, so 16 keys per door.",
            thinkingPrompt: "Can you check your answer using multiplication?"
        },
        {
            id: "math-009",
            type: "text",
            category: "math",
            skill: "multiplication",
            difficulty: 1,
            challenge: false,
            question: "There are <b>16</b> drones and each needs <b>100</b> micro-charges. How many micro-charges are needed?",
            answer: "1600",
            hint: "Multiplying by 100 moves the digits two places in place value.",
            explanation: "16 × 100 = 1,600.",
            thinkingPrompt: "Why does the value become 100 times larger?"
        },
        {
            id: "math-010",
            type: "text",
            category: "math",
            skill: "halving_doubling",
            difficulty: 3,
            challenge: false,
            question: "Find <b>18 × 15</b>. Try changing one factor so the multiplication becomes easier.",
            answer: "270",
            hint: "Halve 18 and double 15. The product stays the same.",
            explanation: "18 × 15 = 9 × 30 = 270.",
            thinkingPrompt: "Why is halving one factor and doubling the other allowed?"
        },
        {
            id: "math-011",
            type: "mcq",
            category: "math",
            skill: "geometry",
            difficulty: 2,
            challenge: false,
            question: "A four-sided shape has four equal sides, but its angles are not right angles. What is it?",
            options: ["Rectangle", "Trapezoid", "Rhombus", "Square"],
            answer: "Rhombus",
            hint: "A square has four equal sides AND four right angles. Which option only requires equal sides?",
            explanation: "A rhombus has four equal sides and does not require right angles.",
            thinkingPrompt: "What extra clue would make it definitely a square?"
        },
        {
            id: "logic-001",
            type: "mcq",
            category: "logic",
            skill: "pattern_recognition",
            difficulty: 1,
            challenge: false,
            question: "The pattern is: <b>Blue Square, Red Triangle, Blue Square, Red Triangle...</b> What is the 9th item?",
            options: ["Blue Square", "Red Triangle", "Blue Triangle", "Red Square"],
            answer: "Blue Square",
            hint: "Look at the odd-numbered positions.",
            explanation: "The pattern repeats every two items, so positions 1, 3, 5, 7, and 9 are Blue Squares.",
            thinkingPrompt: "What is the 100th item?"
        },

        {
            id: "math-012",
            type: "text",
            category: "math",
            skill: "area",
            difficulty: 2,
            challenge: false,
            question: "A robot roof is made from two rectangles. One is <b>8 × 3</b> feet and the other is <b>5 × 4</b> feet. What is their combined area?",
            answer: "44",
            hint: "Find each rectangle's area, then combine them.",
            explanation: "8 × 3 = 24 and 5 × 4 = 20. Together they cover 44 square feet.",
            thinkingPrompt: "How is area different from perimeter?"
        },
        {
            id: "logic-002",
            type: "mcq",
            category: "logic",
            skill: "constraint_reasoning",
            difficulty: 2,
            challenge: false,
            question: "A code is an even number greater than 60, less than 70, and a multiple of 8. What is it?",
            options: ["62", "64", "66", "68"],
            answer: "64",
            hint: "List the multiples of 8 near 60.",
            explanation: "64 is between 60 and 70, is even, and is 8 × 8.",
            thinkingPrompt: "Which clue was most useful for eliminating choices?"
        },
        {
            id: "logic-003",
            type: "text",
            category: "logic",
            skill: "sequence_rules",
            difficulty: 2,
            challenge: false,
            question: "A sensor reports: <b>3, 6, 12, 24, ___</b>. What comes next?",
            answer: "48",
            hint: "Compare each number with the one before it.",
            explanation: "Each number is doubled, so 24 × 2 = 48.",
            thinkingPrompt: "Can you invent a different pattern that starts 3, 6, 12, 24?"
        },
        {
            id: "math-013",
            type: "text",
            category: "math",
            skill: "fractions",
            difficulty: 2,
            challenge: false,
            question: "Marty has <b>32</b> energy canisters and uses <b>3/4</b> of them. How many does he use?",
            answer: "24",
            hint: "Find 1/4 first, then think about three groups of that size.",
            explanation: "32 ÷ 4 = 8, and 8 × 3 = 24.",
            thinkingPrompt: "What fraction is left?"
        },
        {
            id: "math-014",
            type: "text",
            category: "math",
            skill: "regrouping",
            difficulty: 1,
            challenge: false,
            question: "Two power grids produce <b>76</b> and <b>88</b> units. What is the total?",
            answer: "164",
            hint: "Add the ones first. What happens when 6 + 8 is more than 9?",
            explanation: "76 + 88 = 164.",
            thinkingPrompt: "Can you solve it mentally without the standard written algorithm?"
        },
        {
            id: "math-015",
            type: "text",
            category: "math",
            skill: "mean",
            difficulty: 3,
            challenge: false,
            question: "Three test laps take <b>110, 130, and 150 seconds</b>. What is their average time?",
            answer: "130",
            hint: "An average is the total shared equally among the three laps.",
            explanation: "110 + 130 + 150 = 390; 390 ÷ 3 = 130.",
            thinkingPrompt: "Why does 130 make sense before you calculate?"
        },
        {
            id: "logic-004",
            type: "text",
            category: "logic",
            skill: "working_backward",
            difficulty: 3,
            challenge: false,
            question: "Marty starts with some gems. He doubles them, then adds 8, ending with <b>38</b>. How many did he start with?",
            answer: "15",
            hint: "Undo the last operation first.",
            explanation: "Undo +8: 38 − 8 = 30. Undo ×2: 30 ÷ 2 = 15.",
            thinkingPrompt: "How could you prove 15 is the starting number?"
        },
        {
            id: "math-016",
            type: "mcq",
            category: "math",
            skill: "fraction_comparison",
            difficulty: 2,
            challenge: false,
            question: "Which battery is fuller: <b>4/5</b> or <b>3/4</b>?",
            options: ["4/5", "3/4"],
            answer: "4/5",
            hint: "Compare both fractions to 1 whole, or convert them to a common denominator.",
            explanation: "4/5 = 80% and 3/4 = 75%, so 4/5 is greater.",
            thinkingPrompt: "Can you compare them without using percentages?"
        },
        {
            id: "math-017",
            type: "text",
            category: "math",
            skill: "median",
            difficulty: 3,
            challenge: false,
            question: "The readings are <b>14, 18, 22, 28</b>. What number is exactly halfway between the two middle readings?",
            answer: "20",
            hint: "The middle readings are 18 and 22. Find the number equally far from both.",
            explanation: "20 is 2 away from 18 and 2 away from 22.",
            thinkingPrompt: "What would the median be if 28 changed to 100?"
        },
        {
            id: "math-018",
            type: "text",
            category: "math",
            skill: "multiplication_strategy",
            difficulty: 2,
            challenge: false,
            question: "Find <b>16 × 25</b> using a strategy that makes 25 friendly.",
            answer: "400",
            hint: "25 is one-fourth of 100.",
            explanation: "16 × 25 = 16 × 100 ÷ 4 = 1,600 ÷ 4 = 400.",
            thinkingPrompt: "Can you find another mental strategy?"
        },
        {
            id: "math-019",
            type: "text",
            category: "math",
            skill: "range",
            difficulty: 2,
            challenge: false,
            question: "Temperature readings are <b>32, 19, 84, 51</b>. What is the range?",
            answer: "65",
            hint: "Range is the distance from the smallest value to the largest.",
            explanation: "84 − 19 = 65.",
            thinkingPrompt: "What does a larger range tell you about a data set?"
        },
        {
            id: "math-020",
            type: "text",
            category: "math",
            skill: "compensation_subtraction",
            difficulty: 2,
            challenge: false,
            question: "Find <b>154 − 49</b> using a mental-math strategy.",
            answer: "105",
            hint: "Subtract 50 instead, then correct the answer.",
            explanation: "154 − 50 = 104, then add 1 back: 105.",
            thinkingPrompt: "Why did we need to add 1 back?"
        },
        {
            id: "logic-005",
            type: "mcq",
            category: "logic",
            skill: "ordering",
            difficulty: 2,
            challenge: false,
            question: "Drone A is faster than B. B is faster than C. C is faster than D. Which is slowest?",
            options: ["Drone A", "Drone B", "Drone C", "Drone D"],
            answer: "Drone D",
            hint: "Put the drones in order from fastest to slowest.",
            explanation: "A > B > C > D, so D is slowest.",
            thinkingPrompt: "If D becomes faster than B, what can you still prove?"
        },
        {
            id: "robot-001",
            type: "text",
            category: "robotics",
            skill: "combinations",
            difficulty: 2,
            challenge: false,
            question: "Marty has <b>4 chassis</b>, <b>3 arm modules</b>, and <b>3 sensor heads</b>. Each robot uses one of each. How many different robots can he build?",
            answer: "36",
            hint: "For every chassis, how many arm-and-sensor combinations are possible?",
            explanation: "4 × 3 × 3 = 36 different combinations.",
            thinkingPrompt: "What if Marty had 4 sensor heads instead?"
        },
        {
            id: "math-021",
            type: "mcq",
            category: "math",
            skill: "symmetry",
            difficulty: 2,
            challenge: false,
            question: "How many lines of symmetry does a regular octagon have?",
            options: ["4", "6", "8", "10"],
            answer: "8",
            hint: "A regular polygon has one matching symmetry line for each side.",
            explanation: "A regular octagon has 8 lines of symmetry.",
            thinkingPrompt: "Would an irregular octagon necessarily have 8? Why?"
        },
        {
            id: "math-022",
            type: "text",
            category: "math",
            skill: "multiplication_by_8",
            difficulty: 1,
            challenge: false,
            question: "Find <b>7 × 8</b> using doubling as much as possible.",
            answer: "56",
            hint: "Double 7 three times.",
            explanation: "7 → 14 → 28 → 56.",
            thinkingPrompt: "Why does three doublings equal multiplying by 8?"
        },
        {
            id: "math-023",
            type: "mcq",
            category: "math",
            skill: "elapsed_time",
            difficulty: 2,
            challenge: false,
            question: "A test starts at <b>3:40 PM</b> and ends at <b>4:25 PM</b>. How long does it take?",
            options: ["35 minutes", "40 minutes", "45 minutes", "50 minutes"],
            answer: "45 minutes",
            hint: "Count to 4:00 first, then continue to 4:25.",
            explanation: "20 minutes to 4:00 plus 25 minutes = 45 minutes.",
            thinkingPrompt: "How would you solve it if the test ended at 5:10?"
        },
        {
            id: "logic-006",
            type: "mcq",
            category: "logic",
            skill: "inverse_checking",
            difficulty: 2,
            challenge: false,
            question: "Marty says <b>27 × 4 = 108</b>. Which check would prove his answer?",
            options: ["108 ÷ 4 = 27", "108 ÷ 27 = 5", "27 + 4 = 31", "108 − 4 = 104"],
            answer: "108 ÷ 4 = 27",
            hint: "Use the inverse operation of multiplication.",
            explanation: "108 ÷ 4 returns to 27, confirming the multiplication.",
            thinkingPrompt: "What other check could you use?"
        },
        {
            id: "logic-007",
            type: "mcq",
            category: "logic",
            skill: "probability",
            difficulty: 3,
            challenge: false,
            question: "A box has 12 cards. 3 are winners and 9 are decoys. What is the chance of picking a winner on the first try?",
            options: ["1 in 3", "1 in 4", "3 in 4", "1 in 12"],
            answer: "1 in 4",
            hint: "Think about 3 winners out of 12 total cards.",
            explanation: "3/12 simplifies to 1/4, or 1 in 4.",
            thinkingPrompt: "Would the chance change if all 12 cards were shuffled again?"
        },
        {
            id: "math-024",
            type: "text",
            category: "math",
            skill: "friendly_addition",
            difficulty: 2,
            challenge: false,
            question: "Add <b>36 + 47 + 14 + 23</b>. Look for pairs that make friendly numbers.",
            answer: "120",
            hint: "Can you pair numbers that make 50 or 70?",
            explanation: "36 + 14 = 50 and 47 + 23 = 70. Total = 120.",
            thinkingPrompt: "How did rearranging the numbers help?"
        },
        {
            id: "logic-008",
            type: "mcq",
            category: "logic",
            skill: "elimination",
            difficulty: 2,
            challenge: false,
            question: "A hidden core is in Sector A, B, C, or D. It is not A, not B, and is in an odd-numbered sector (A=1, B=2, C=3, D=4). Where is it?",
            options: ["Sector A", "Sector B", "Sector C", "Sector D"],
            answer: "Sector C",
            hint: "Cross out the impossible sectors first.",
            explanation: "A and B are eliminated. D is even, leaving C.",
            thinkingPrompt: "Which clue could you remove and still solve it?"
        },
        {
            id: "math-025",
            type: "text",
            category: "math",
            skill: "median",
            difficulty: 2,
            challenge: false,
            question: "Put these times in order: <b>48, 22, 60, 35, 29</b>. What is the median?",
            answer: "35",
            hint: "Sort them from smallest to largest, then find the middle one.",
            explanation: "22, 29, 35, 48, 60 → 35 is in the middle.",
            thinkingPrompt: "What happens to the median if the largest number gets much bigger?"
        },
        {
            id: "logic-009",
            type: "text",
            category: "logic",
            skill: "multi_step_reasoning",
            difficulty: 2,
            challenge: false,
            question: "A lab has <b>4 crates</b> with <b>9 gears</b> each. It receives 10 more gears and uses 8 for repairs. How many remain?",
            answer: "38",
            hint: "Handle the events in the order they happen.",
            explanation: "4 × 9 = 36; 36 + 10 = 46; 46 − 8 = 38.",
            thinkingPrompt: "Which step would you check first if your final answer seemed wrong?"
        },
        {
            id: "math-026",
            type: "text",
            category: "math",
            skill: "difference",
            difficulty: 1,
            challenge: false,
            question: "Marty scores <b>95</b> points and the benchmark is <b>47</b>. How many points higher is Marty?",
            answer: "48",
            hint: "Find the distance from 47 to 95.",
            explanation: "95 − 47 = 48.",
            thinkingPrompt: "Can you calculate it by counting up instead?"
        },
        {
            id: "math-027",
            type: "text",
            category: "math",
            skill: "multiplication_compensation",
            difficulty: 3,
            challenge: false,
            question: "Find <b>8 × 99</b> without doing the standard multiplication algorithm.",
            answer: "792",
            hint: "99 is one less than 100.",
            explanation: "8 × 100 = 800, then subtract one group of 8: 792.",
            thinkingPrompt: "How would this strategy work for 12 × 99?"
        },
        {
            id: "math-028",
            type: "text",
            category: "math",
            skill: "money",
            difficulty: 2,
            challenge: false,
            question: "Marty buys <b>3 books at $9 each</b> and pays with $50. How much change does he receive?",
            answer: "23",
            hint: "Find the total cost first.",
            explanation: "3 × $9 = $27. $50 − $27 = $23.",
            thinkingPrompt: "What mental strategy makes $50 − $27 easy?"
        },
        {
            id: "logic-010",
            type: "mcq",
            category: "logic",
            skill: "deductive_matching",
            difficulty: 2,
            challenge: false,
            question: "Marty, Leo, and Ava each choose Math, Logic, or Science. Leo chooses Science. Ava does not choose Math. What must Ava choose?",
            options: ["Math", "Logic", "Science"],
            answer: "Logic",
            hint: "Each person gets a different subject.",
            explanation: "Leo has Science. Ava cannot have Math, so Ava must have Logic.",
            thinkingPrompt: "What subject is left for Marty?"
        },
        {
            id: "math-029",
            type: "text",
            category: "math",
            skill: "multiplication_decomposition",
            difficulty: 2,
            challenge: false,
            question: "Marty completes <b>8 phases</b> and earns <b>16 badges per phase</b>. How many badges does he earn?",
            answer: "128",
            hint: "Break 16 into 10 and 6, or double 16 eight times.",
            explanation: "8 × 16 = 8 × 10 + 8 × 6 = 80 + 48 = 128.",
            thinkingPrompt: "Can you solve 16 × 8 using a different strategy?"
        },
        {
            id: "robot-002",
            type: "text",
            category: "robotics",
            skill: "optimization",
            difficulty: 3,
            challenge: true,
            question: "A robot must visit three stations: <b>A, B, and C</b>. From the start, A is 4 steps away, B is 7, and C is 5. After each station, the robot must return to the start. Which station should it visit first if you want the robot to travel the shortest total distance? <br><br><b>Bonus:</b> Does the order actually change the total distance?",
            answer: "The order does not change the total distance",
            hint: "Because the robot returns to the start after every station, calculate each complete trip separately.",
            explanation: "Each station's round trip is fixed: A=8, B=14, C=10. The total is 32 steps no matter the order.",
            thinkingPrompt: "What would make the order matter?"
        },
        {
            id: "robot-003",
            type: "text",
            category: "robotics",
            skill: "combinations",
            difficulty: 3,
            challenge: true,
            question: "Marty can build a robot with <b>2 body types</b>, <b>3 wheel types</b>, and <b>2 sensor types</b>. How many different robots are possible?",
            answer: "12",
            hint: "Choose one option from each category. Multiply the number of choices.",
            explanation: "2 × 3 × 2 = 12 combinations.",
            thinkingPrompt: "If Marty could choose two different sensor types at once, how would the problem change?"
        },
        {
            id: "robot-004",
            type: "text",
            category: "robotics",
            skill: "algorithm_design",
            difficulty: 3,
            challenge: true,
            question: "A delivery robot follows these rules: <b>move forward 2 squares, turn right, move forward 2 squares, turn right</b>. Starting at the bottom-left corner of a square, where will it be after repeating the instructions twice?",
            answer: "Back at the starting position",
            hint: "Draw the path. Each pair of turns changes the robot's direction.",
            explanation: "The robot makes a 2-by-2 square and returns to its starting point after the second repeat.",
            thinkingPrompt: "What if the robot repeated the instructions three times?"
        },
        {
            id: "robot-005",
            type: "mcq",
            category: "robotics",
            skill: "debugging",
            difficulty: 3,
            challenge: true,
            question: "A robot should move <b>forward 5</b>, turn right, then move forward 3. Instead it moves forward 5, turns right, then moves forward 5. Which instruction is most likely wrong?",
            options: ["Move forward 5", "Turn right", "Move forward 3", "All of them"],
            answer: "Move forward 3",
            hint: "Compare what the robot actually did with the intended final movement.",
            explanation: "The first two instructions match. The last movement should be 3, not 5.",
            thinkingPrompt: "What information would you log to find this bug automatically?"
        },
        {
            id: "beyblade-001",
            type: "text",
            category: "beyblade",
            skill: "tournament_math",
            difficulty: 2,
            challenge: false,
            question: "Eight Beyblades enter a tournament. In each battle, one Beyblade is eliminated. How many battles are needed to find one champion?",
            answer: "7",
            hint: "Start with 8 competitors. Each battle removes exactly one competitor.",
            explanation: "You need to eliminate 7 Beyblades to leave 1 champion, so 7 battles are needed.",
            thinkingPrompt: "How many battles would be needed for 16 Beyblades?"
        },
        {
            id: "beyblade-002",
            type: "mcq",
            category: "beyblade",
            skill: "probability",
            difficulty: 2,
            challenge: false,
            question: "Marty spins a Beyblade 20 times. It wins 15 times. Which statement is closest to the experimental win rate?",
            options: ["15%", "25%", "75%", "95%"],
            answer: "75%",
            hint: "15 out of 20 can be simplified to a familiar fraction.",
            explanation: "15/20 = 3/4 = 75%.",
            thinkingPrompt: "Would 15 wins out of 20 guarantee a 75% win rate next week?"
        },
        {
            id: "beyblade-003",
            type: "text",
            category: "beyblade",
            skill: "data_reasoning",
            difficulty: 3,
            challenge: false,
            question: "Three Beyblades score 82, 91, and 87 points. What is the <b>average</b> score?",
            answer: "86.67",
            hint: "Add the three scores and divide by 3. A decimal answer is okay.",
            explanation: "82 + 91 + 87 = 260. 260 ÷ 3 = 86.67 approximately.",
            thinkingPrompt: "Why might the average not be a whole number?"
        },
        {
            id: "beyblade-004",
            type: "text",
            category: "beyblade",
            skill: "combinations",
            difficulty: 3,
            challenge: true,
            question: "Four Beyblades are named A, B, C, and D. Each pair battles once. How many different battles are there?",
            answer: "6",
            hint: "List the pairs without counting A vs B and B vs A as different.",
            explanation: "The unique pairs are AB, AC, AD, BC, BD, CD: 6 battles.",
            thinkingPrompt: "How many unique battles would 5 Beyblades create?"
        },
        {
            id: "race-001",
            type: "text",
            category: "racing",
            skill: "distance_time",
            difficulty: 2,
            challenge: false,
            question: "A race car travels <b>12 meters every second</b>. How far does it travel in 5 seconds?",
            answer: "60",
            hint: "Five groups of 12.",
            explanation: "12 × 5 = 60 meters.",
            thinkingPrompt: "How far would it travel in 10 seconds?"
        },
        {
            id: "race-002",
            type: "mcq",
            category: "racing",
            skill: "speed_comparison",
            difficulty: 2,
            challenge: false,
            question: "Car A travels 50 meters in 5 seconds. Car B travels 48 meters in 4 seconds. Which car is faster?",
            options: ["Car A", "Car B", "They are the same"],
            answer: "Car B",
            hint: "Think about how many meters each car travels in one second.",
            explanation: "A travels 10 m/s. B travels 12 m/s, so B is faster.",
            thinkingPrompt: "Why is comparing total distance alone misleading?"
        },
        {
            id: "race-003",
            type: "text",
            category: "racing",
            skill: "elapsed_time",
            difficulty: 2,
            challenge: false,
            question: "Marty's race starts at <b>2:35</b> and ends at <b>3:12</b>. How many minutes long is the race?",
            answer: "37",
            hint: "Count from 2:35 to 3:00, then from 3:00 to 3:12.",
            explanation: "25 + 12 = 37 minutes.",
            thinkingPrompt: "Can you solve it by subtracting the times another way?"
        },
        {
            id: "race-004",
            type: "text",
            category: "racing",
            skill: "experimental_design",
            difficulty: 3,
            challenge: true,
            question: "Marty wants to know whether a higher ramp makes a toy car travel farther. He has three ramps: 10 cm, 20 cm, and 30 cm. What should he keep the same in every test so the experiment is fair?",
            answer: "The car and track/surface should stay the same",
            hint: "Change only one variable if you want to know what caused the difference.",
            explanation: "Keep the car, track surface, starting position, and other conditions the same. Change only ramp height.",
            thinkingPrompt: "What would happen if he changed the car too?"
        },
        {
            id: "science-001",
            type: "text",
            category: "science",
            skill: "prediction",
            difficulty: 2,
            challenge: false,
            question: "Marty puts the same toy car on three surfaces: smooth wood, carpet, and a towel. Before testing, which surface would you predict lets it travel farthest?",
            answer: "smooth wood",
            hint: "Think about which surface gives the car the least resistance.",
            explanation: "A smooth surface usually creates less friction, so the car should travel farther.",
            thinkingPrompt: "What evidence would convince you that your prediction was wrong?"
        },
        {
            id: "science-002",
            type: "text",
            category: "science",
            skill: "variables",
            difficulty: 3,
            challenge: false,
            question: "Marty tests whether heavier toy cars travel farther down the same ramp. What is the <b>independent variable</b>—the thing he changes?",
            answer: "the weight of the car",
            hint: "Ask: What is Marty deliberately changing?",
            explanation: "He changes the car's weight while keeping other conditions the same.",
            thinkingPrompt: "What should he measure as the result?"
        },
        {
            id: "science-003",
            type: "mcq",
            category: "science",
            skill: "evidence",
            difficulty: 2,
            challenge: false,
            question: "Marty predicts a blue car will travel farther than a red car. He runs 10 fair tests and the red car travels farther 9 times. What should he conclude?",
            options: ["The prediction was supported", "The prediction was not supported", "The test proves blue cars never travel far", "There is no useful information"],
            answer: "The prediction was not supported",
            hint: "Compare the prediction with what happened in most of the tests.",
            explanation: "The results mostly went against the prediction, so the prediction was not supported by this experiment.",
            thinkingPrompt: "What should Marty do next?"
        },
        {
            id: "science-004",
            type: "text",
            category: "science",
            skill: "data_interpretation",
            difficulty: 3,
            challenge: true,
            question: "A plant grows 2 cm in Week 1, 3 cm in Week 2, 5 cm in Week 3, and 5 cm in Week 4. What is the total growth over four weeks?",
            answer: "15",
            hint: "Add the growth from each week.",
            explanation: "2 + 3 + 5 + 5 = 15 cm.",
            thinkingPrompt: "What additional measurement would help you understand why growth changed?"
        },
        {
            id: "puzzle-001",
            type: "text",
            category: "logic",
            skill: "binary_search",
            difficulty: 3,
            challenge: true,
            question: "I'm thinking of a number from <b>1 to 100</b>. You can ask yes/no questions. What is the best first question if you want to eliminate as many possibilities as possible?",
            answer: "Is the number greater than 50?",
            hint: "Try to split the possible numbers into two groups of about equal size.",
            explanation: "Asking whether the number is greater than 50 splits 100 possibilities into two groups of 50. This is the basic idea behind binary search.",
            thinkingPrompt: "What question would you ask next if the answer were yes?"
        },
        {
            id: "puzzle-002",
            type: "mcq",
            category: "logic",
            skill: "multiple_solutions",
            difficulty: 3,
            challenge: true,
            question: "Which statement is definitely true? <br><br>A: Every square is a rectangle.<br>B: Every rectangle is a square.<br>C: Every triangle has four sides.<br>D: Every circle has corners.",
            options: ["A", "B", "C", "D"],
            answer: "A",
            hint: "Think about the definition of a square and what properties it has.",
            explanation: "A square has four right angles and opposite sides parallel, so it meets the definition of a rectangle.",
            thinkingPrompt: "Can you explain why B is not always true?"
        },
        {
            id: "puzzle-003",
            type: "text",
            category: "logic",
            skill: "constraint_reasoning",
            difficulty: 3,
            challenge: true,
            question: "Three robots—A, B, and C—finish a race. A is not first. B finishes before C. Who could be first?",
            answer: "B",
            hint: "B must be before C, and A cannot be first.",
            explanation: "B can be first. A cannot be first, and C cannot be first because B must finish before C.",
            thinkingPrompt: "Can you list all possible finishing orders?"
        },
        {
            id: "puzzle-004",
            type: "text",
            category: "logic",
            skill: "pattern_creation",
            difficulty: 2,
            challenge: false,
            question: "Create a number pattern that begins <b>2, 5, 8</b>. Give the next three numbers and explain your rule.",
            answer: "11, 14, 17",
            hint: "Look at the difference between consecutive numbers.",
            explanation: "A simple rule is add 3 each time: 2, 5, 8, 11, 14, 17.",
            thinkingPrompt: "Can you invent a different rule that still starts 2, 5, 8?"
        },
        {
            id: "puzzle-005",
            type: "text",
            category: "logic",
            skill: "proof",
            difficulty: 4,
            challenge: true,
            question: "Marty says: <b>All robots with 4 wheels can move.</b> He finds a robot with 4 wheels that cannot move. What does this tell him about his statement?",
            answer: "The statement is false",
            hint: "One counterexample is enough to disprove a statement that says something is true for every case.",
            explanation: "The robot that cannot move is a counterexample, so the claim that all 4-wheel robots can move is false.",
            thinkingPrompt: "Can you give an example of a statement that would need many tests before you believed it?"
        },
        {
            id: "ai-001",
            type: "text",
            category: "ai",
            skill: "computational_thinking",
            difficulty: 2,
            challenge: false,
            question: "An AI robot is told: <b>IF the battery is below 20, return to base. OTHERWISE, continue.</b> Its battery is 15. What should it do?",
            answer: "return to base",
            hint: "Which condition is true: below 20 or not below 20?",
            explanation: "15 is below 20, so the robot follows the first rule and returns to base.",
            thinkingPrompt: "What should happen when the battery is exactly 20?"
        },
        {
            id: "ai-002",
            type: "text",
            category: "ai",
            skill: "algorithms",
            difficulty: 3,
            challenge: false,
            question: "Marty wants an AI to sort three numbers from smallest to largest. The numbers are <b>7, 3, 5</b>. What should the first step accomplish?",
            answer: "identify or compare the smallest number",
            hint: "Before you can put everything in order, you need to know which value belongs first.",
            explanation: "A sorting process needs to compare values and determine their relative order. The smallest value, 3, belongs first.",
            thinkingPrompt: "What could the next step be after finding 3?"
        },
        {
            id: "ai-003",
            type: "mcq",
            category: "ai",
            skill: "critical_thinking",
            difficulty: 3,
            challenge: true,
            question: "An AI says: <b>\"Every red car is faster than every blue car.\"</b> Marty sees one red car that is slower than one blue car. What should he conclude?",
            options: ["The AI's statement is disproved", "The AI must be correct", "The colors must be wrong", "There is not enough information to challenge the statement"],
            answer: "The AI's statement is disproved",
            hint: "The statement says every red car is faster. What does one counterexample do?",
            explanation: "One red car that is slower than a blue car is enough to disprove the universal statement.",
            thinkingPrompt: "Why is this an important way to check AI answers?"
        },
        {
            id: "ai-004",
            type: "text",
            category: "ai",
            skill: "debugging",
            difficulty: 3,
            challenge: true,
            question: "Marty gives an AI these instructions: <b>1. Pick up the package. 2. Put the package in the truck. 3. Drive to the delivery address. 4. Pick up the package.</b> What is wrong with the algorithm?",
            answer: "Step 4 is unnecessary or out of order",
            hint: "The package was already picked up in Step 1 and delivered after Step 3.",
            explanation: "After the package is put in the truck and delivered, picking it up again makes no sense. The instructions contain an unnecessary/out-of-order step.",
            thinkingPrompt: "What test could you run to catch this kind of mistake?"
        },
        {
            id: "boss-001",
            type: "text",
            category: "math",
            skill: "combinations",
            difficulty: 4,
            challenge: true,
            question: "<b>ROBOT BOSS CHALLENGE:</b> Marty has 24 wheels. A small robot needs 4 wheels and a large robot needs 6 wheels. He wants to use all 24 wheels. How many different combinations of small and large robots can he build? Give every possibility.",
            answer: "6 small; 3 small and 2 large; 0 small and 4 large",
            hint: "Start with all small robots. Replace some small robots with large ones while still using exactly 24 wheels.",
            explanation: "The possibilities are 6 small; 3 small + 2 large; and 4 large. Each uses exactly 24 wheels.",
            thinkingPrompt: "How can you prove that you found every possible combination?"
        },

        {
            id: "boss-002",
            type: "text",
            category: "racing",
            skill: "optimization",
            difficulty: 4,
            challenge: true,
            question: "<b>RACING BOSS CHALLENGE:</b> Marty has 20 seconds of race time. A boost makes the car travel 4 extra meters per second for each second it is used. If he can use the boost for 1, 2, 3, or 4 seconds, which choice gives the greatest total extra distance?",
            answer: "4 seconds",
            hint: "Calculate the extra distance for each possible boost time.",
            explanation: "1 second adds 4 m, 2 adds 8 m, 3 adds 12 m, and 4 adds 16 m. Four seconds gives the greatest extra distance.",
            thinkingPrompt: "What other constraint would make a shorter boost better?"
        },
        {
            id: "boss-003",
            type: "text",
            category: "science",
            skill: "experimental_design",
            difficulty: 4,
            challenge: true,
            question: "<b>SCIENCE BOSS CHALLENGE:</b> Marty wants to know whether ramp height affects how far a car travels. He tests a 10 cm ramp with a heavy car, a 20 cm ramp with a light car, and a 30 cm ramp with a heavy car. Can he fairly conclude that ramp height caused the differences? Explain.",
            answer: "No",
            hint: "Look for another variable that changed besides ramp height.",
            explanation: "No. Both ramp height and car weight changed, so the experiment does not isolate ramp height as the cause.",
            thinkingPrompt: "Design a fair version of the experiment."
        },
        {
            id: "boss-004",
            type: "text",
            category: "logic",
            skill: "proof",
            difficulty: 4,
            challenge: true,
            question: "<b>PUZZLE BOSS:</b> There are three boxes. Exactly one contains a prize. Box A says \"The prize is not in B.\" Box B says \"The prize is in C.\" Box C says \"The prize is not in C.\" Exactly <b>one</b> statement is true. Where is the prize?",
            answer: "B",
            hint: "Test A, then B, then C as the possible prize location. Count how many statements are true each time.",
            explanation: "If the prize is in B: A is false, B is false, C is true—exactly one statement is true. The other locations produce more than one true statement.",
            thinkingPrompt: "Why is testing every possibility a valid proof here?"
        },
        {
            id: "boss-005",
            type: "text",
            category: "ai",
            skill: "critical_thinking",
            difficulty: 4,
            challenge: true,
            question: "<b>AI BOSS:</b> An AI answers 9 out of 10 questions correctly. Marty asks it one question and gets an answer he thinks is wrong. Should he assume the AI is wrong just because its overall score is 90%? Explain.",
            answer: "No",
            hint: "An overall success rate describes many questions, not whether this particular answer is correct.",
            explanation: "No. A 90% accuracy rate does not tell us whether this particular answer is correct. Marty should verify the specific claim.",
            thinkingPrompt: "What could Marty do to verify the answer?"
        },
        {
            id: "boss-006",
            type: "text",
            category: "beyblade",
            skill: "data_reasoning",
            difficulty: 4,
            challenge: true,
            question: "<b>BEYBLADE BOSS:</b> Beyblade A wins 8 of 10 battles. Beyblade B wins 15 of 20. Which has the higher experimental win rate?",
            answer: "Beyblade A",
            hint: "Turn both results into percentages or fractions with the same denominator.",
            explanation: "A wins 8/10 = 80%. B wins 15/20 = 75%. So A has the higher experimental win rate.",
            thinkingPrompt: "Why can a smaller number of battles still produce a higher win rate?"
        },
        {
            id: "boss-007",
            type: "text",
            category: "math",
            skill: "multi_step_reasoning",
            difficulty: 4,
            challenge: true,
            question: "<b>FINAL MISSION:</b> Marty has 100 energy units. Each robot mission costs 7 units. He completes 8 missions, then receives 30 new units. How many units remain?",
            answer: "74",
            hint: "Track the energy in the order events happen.",
            explanation: "8 × 7 = 56 used. 100 − 56 = 44. Then 44 + 30 = 74.",
            thinkingPrompt: "Can you write the whole problem as one mathematical expression?"
        }
    ]
};
